enableScripts: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-dotenv.cjs
    spec: "https://unpkg.com/yarn-plugin-dotenv/bundles/@yarnpkg/plugin-dotenv.js"

# httpProxy: ${BERRY_RC_HTTP_PROXY-http://127.0.0.1:51457}
httpProxy: ${BERRY_RC_HTTP_PROXY-}

# httpsProxy: ${BERRY_RC_HTTPS_PROXY-http://127.0.0.1:51457}
httpsProxy: ${BERRY_RC_HTTPS_PROXY-}

# npmRegistryServer: ${BERRY_RC_NPM_REGISTRY-https://registry.npm.taobao.org}
npmRegistryServer: ${BERRY_RC_NPM_REGISTRY-}

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-2.4.0.cjs
