version: '3'
services:
  database:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data
