version: '3.6'
networks:
  # docker network create public
  public:
    external: true
services:
  frontend:
    build: ./
    restart: always
    ports:
      - '80'
    networks:
      - public
      - default
  api:
    build: ./server/
    restart: always
    depends_on:
      - redis
    ports:
      - '3000'
    networks:
      - public
      - default
    environment:
      - 'OAUTH_GITHUB_CLIENT_ID=<OAUTH_GITHUB_CLIENT_ID>'
      - 'OAUTH_GITHUB_CLIENT_SECRET=<OAUTH_GITHUB_CLIENT_SECRET>'
      - 'FRONTEND_BASE_URL=<FRONTEND_BASE_URL>'
      - 'REDIS_HOST=redis'
  redis:
    image: redis
    restart: always
