version: '3.6'
networks:
  # docker network create public
  public:
    external: true
services:
  frontend:
    build: ./
    restart: always
    ports:
      - "80"
    networks:
      - public
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=talks'
      - 'traefik.frontend.rule=Host:talks.mindfine.com'
      - 'traefik.port=80'
