version: "3"

services:
  api:
    depends_on:
      - db
    user: node
    stdin_open: true
    tty: true
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile.development
      args:
        CHINA_MIRROR: "true"
    volumes:
      - ./api:/home/node
    env_file:
      - .env.local
    command: yarn start:dev
    ports:
      - 3001:3001

  db:
    hostname: db
    image: postgres:14-alpine
    env_file:
      - .env.local
    ports:
      - 5432:5432
    volumes:
      - ./scripts/pgsql:/docker-entrypoint-initdb.d
      - postgresql:/var/lib/postgresql/data

  frontend:
    depends_on:
      - api
    user: node
    stdin_open: true
    tty: true
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.development
      args:
        CHINA_MIRROR: "true"
    volumes:
      - ./frontend:/home/node
    env_file:
      - .env.local
    command: yarn start
    ports:
      - 3000:3000

volumes:
  postgresql:
