server:
  port: 3000
  loggerLevel: ['error', 'warn', 'debug', 'log', 'verbose']
  cors: { origin: true, credentials: true }

db:
  type: 'postgres'
  port: 5433
  database: 'nest'
  loggerLevel: 'all'
  maxQueryExecutionTime: 500

jwt:
  expiresIn: 3600
  secret: 'topSecret51'
