version: '3'
services:
  pg:
    image: 'postgres:11.5'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
#    volumes:
#      - postgres:/var/lib/postgresql/data
#volumes:
#  postgres: ~
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
